_target_: src.models.enhancer_module.EnhancerLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 2

net:
  _target_: src.models.components.ResUNet.ResUNet
  in_ch: 1
  chs: [64, 128, 256, 512, 1024]
  ndim: 2
  out_ch: 1

# compile model for faster training with pytorch 2.0
compile: false

output_path: /home/gabriel/fingerprint-enhancement/output/
