_target_: src.models.enhancer_module.EnhancerLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.my_network.FingerGAN
  in_ch: 1
  chs: [64, 128, 256, 512, 1024]
  ndim: 2
  out_ch: 1

# compile model for faster training with pytorch 2.0
compile: false

output_path: /home/gabriel/fingerprint-enhancement/output/
