# @package _global_

defaults:
  - _self_
  - data: enhancer_predict # choose datamodule with `predict_dataloader()`
  - model: enhancer
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: /home/gabriel/fingerprint-enhancement/logs/train/runs/2025-05-18_04-36-05/checkpoints/last.ckpt
ckpt_path: /home/seabra/fingerprint-enhancement/logs/train/runs/2025-06-27_12-40-56/checkpoints/epoch_013.ckpt